### ISSUE TITLE
libopenlibm.so.2.1 exported symbols

### ISSUE THREAD

**Issue by ginggs** [JuliaMath/openlibm#127]
I am analyzing the symbols exported by the openlibm 0.5.0 library (libopenlibm.so.2.1).
In Debian, we use [symbols files](https://wiki.debian.org/UsingSymbolsFiles) to track in which versions of libraries new symbols appear and old symbols disappear.

In openlibm 0.5.0, we gained some symbols, like:

```
__scan_nan@Base
cacos@Base
cacosf@Base
```

...and we lost some symbols, like:

```
__fedisableexcept@Base
_scan_nan@Base
gamma@Base
```

This is normal for a library where the SONAME has been bumped.

I did notice that there were several symbols that were missing from the **powerpc** build, for example:

```
_ItL_aT@Base
_ItL_atanhi@Base
_ItL_atanlo@Base
```

...from 0.4 which are still present in 0.5.0 on **amd64** and **i386**, and several symbols names ending in 'l' from 0.4 and 0.5.0, for example:

```
acoshl@Base
acosl@Base
fabsl@Base
```

...which are present on **amd64** and **i386**.

There were also some symbols present on **powerpc** that were only present on **i386** and not present on **amd64**, for example:

```
feclearexcept@Base 0.4
fegetexceptflag@Base 0.4
fegetround@Base
```

I attach a symbols file that covers the architectures on which I have built openlibm so far; **amd64**, **i386**, **powerpc** and **ppc64el**.  I hope the format of the file is easy enough to follow.
The number at the end of a line is the version where the symbol first appeared.
Lines beginning '#MISSING:' are comments which indicate symbols that have been dropped.

Example 1: the following symbol only appears on **i386**, **kfreebsd-i386** and **hurd-i386**:

```
(arch=i386 kfreebsd-i386 hurd-i386)__has_sse@Base 0.4
```

Example 2: the following symbol appears on all architectures except **powerpc** and **ppc64el**:

```
 (arch=!powerpc !ppc64el)__kernel_sinl@Base 0.4
```

Any comments?

[libopenlibm2.symbols.txt](https://github.com/JuliaLang/openlibm/files/170376/libopenlibm2.symbols.txt)

**Comment by ViralBShah** [comment]
I have no idea what to do here. Can you suggest?

**Comment by petercolberg** [comment]
The symbols with suffix `l` are long-double variants available on x86 only. The symbols with prefix `fe` are functions to configure floating-point rounding and exceptions, which are apparently available on x86 only. All of these differences are fine.The symbols prefixed with `_` and `__`, however, are internal symbols that should not be exported from the library. I would suggest setting their [visibility]( https://gcc.gnu.org/wiki/Visibility) to `"hidden"`.

**Comment by ginggs** [comment]
By skipping the failing tests, I was able to extract the **armhf** symbols, which I have added here:
[libopenlibm2-armhf.symbols.txt](https://github.com/JuliaLang/openlibm/files/172500/libopenlibm2-armhf.symbols.txt)

**arm64** (a.k.a. aarch64) still fails early in the build with:
```
Makefile:20: aarch64/Make.files: No such file or directory
make[1]: *** No rule to make target 'aarch64/Make.files'.  Stop.
```

**Comment by yuyichao** [comment]
AArch64 is not supported yet. I was just using system libm for the julia test since I was under the impression that the ARM version also has some issue with floating point flags (test hang?). Are those issue sorted out or should we just add aarch64 support nevertheless?

**Comment by ginggs** [comment]
@petercolberg what you wrote there makes sense, however things are not exactly like that in the symbols file.

e.g. here we have `feclearexcept` which is exported everywhere except **amd64**:
`(arch=i386 kfreebsd-i386 hurd-i386 armhf powerpc ppc64el)feclearexcept@Base 0.4`
while here is `feenableexcept` exported on all **i386** and **amd64** architectures:
`(arch=!armhf !powerpc !ppc64el)feenableexcept@Base 0.4`
and here is `feraiseexcept` exported everywhere:
`feraiseexcept@Base 0.4`

**Comment by ginggs** [comment]
@yuyichao see https://bugs.debian.org/803206 the submitter got it working on arm64, but unfortunately the patch was based on openlibm 0.4.1 and master had diverged somewhat since then.
