### ISSUE TITLE
-Wmaybe-uninitialized when compiling on Raspberry Pi 3

### ISSUE THREAD

**Issue by OllieLollie1** [JuliaMath/openlibm#179]
In the file src/e_lgamma_r.c gcc thinks that nadj is uninitialised. This can be fixed by changing line 208 to  double t, y, z, nadj = 0, p, p1, p2, p3, q, r, w;

**Comment by ViralBShah** [comment]
It is not being used without initializing, so safe to ignore. Or submit a PR if you don't want to see the warning. :-)
