### ISSUE TITLE
aarch64 compile error

### ISSUE THREAD

**Issue by jenkin233** [JuliaMath/openlibm#183]
Hello,
An error occurred when cross compiling with ARCH = aarch64 , the error message says:
`aarch64/fenv.c:40:29: error: invalid initializer
 const fenv_t __fe_dfl_env = `0;
how can i solve it?

**Comment by ViralBShah** [comment]
I suspect this is no longer an issue, since we have binaries for aarch64:

https://github.com/JuliaMath/OpenlibmBuilder/releases

Please reopen with detailed instructions on compiler version, OS, and other details if still an issue.

**Comment by ngam** [comment]
Still an issue:

```clang -D_FORTIFY_SOURCE=2 -isystem $PREFIX/include -mmacosx-version-min=11.0 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/openlibm-0.8.0 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix -fno-builtin -fno-strict-aliasing -fPIC  -std=c99 -Wall -I$SRC_DIR -I$SRC_DIR/include -I$SRC_DIR/aarch64 -I$SRC_DIR/src -DASSEMBLER -D__BSD_VISIBLE -Wno-implicit-function-declaration -I$SRC_DIR/ld128 -c aarch64/fenv.c -o aarch64/fenv.c.o```

See more: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=436152&view=logs&j=ced5d8de-8227-5f3f-33a1-45cf1592c45a&t=f7bcb349-6dca-53ba-d88d-1d9963e119ba

**Comment by ngam** [comment]
Oddly, this does NOT happen for our linux aarch64. Only MacOS cross-compile. 

Maybe something to do with SDK, etc.?

**Comment by ngam** [comment]
And, one more piece of info: Compiles totally fine natively (on mac arm64).

**Comment by ngam** [comment]
As @isuruf fixed it in https://github.com/conda-forge/openlibm-feedstock/pull/29/commits/f83e0bae83c4245e11c76e54e77905e5ed85d101, this seems to resolve this particular problem for osx: `sed -i.bak "s/CC = clang/CC ?= clang/g" Make.inc`

**Comment by ViralBShah** [comment]
Please reopen if still an issue.
