### ISSUE TITLE
Incorrect results in exp

### ISSUE THREAD

**Issue by drorspei** [JuliaMath/openlibm#184]
Hello!

I found some inaccuracy in the result of `exp`: the last bit of `std::exp(std::complex<double>{0., 2 * std::acos(-1) * 1785./16384.}).imag()` is wrong.

This came up at my work where some stuff was sensitive enough to notice the error. The real part is good ^_^

**Comment by kargl** [comment]
You failed to test us which compiler you used (looks like C++).  You failed to tell us the value you obtained and the value you expected.  Some compiler will constant fold the expression, so libm is never involved.

**Comment by kargl** [comment]
Without further information from drorspei, this issue can probably be closed.

**Comment by drorspei** [comment]
Oh crap, I'm sorry. This must be one of the worst pull requests ever :)

I'm using clang++ 5.0 to compile C++ 14 code on Ubuntu 16.04. The code I used was:

```
#include <iostream>

int main() {
    double r = std::exp(std::complex<double>{0., 2 * std::acos(-1) * 1785./16384.}).imag();
    std::cout<< std::hexfloat << r << std::endl;
    return 0;
}
```

I copied the result to a python repl and compared it with a computation to 100 digits of the same number using an arbitrary precision library. I made sure I was computing the right number in python by also printing in C++ the (hex) value of `2 * std::acos(-1) * 1785./16384.` and used the result as input to the exponential function of the arbitrary precision library.

**Comment by nalimilan** [comment]
Concretely, what exact value do you get and what value do you expect? There is no guaranty that the result will be exact AFAIK (precision is of about 1ULP).

**Comment by drorspei** [comment]
I edited in the values in the last comment, probably at the same time as your comment.

If there's no exactness guaranty then that's ok, you can close the issue. I might look into this myself sometime, if the code isn't too hard to get into.

**Comment by kargl** [comment]
The posted C++ is invalid.  clang++ 7.0 generated 7 errors before dying.  Drorpei, I'm finding
 ./testd -S -a 0x1.5e7be2dd1ebcep-1
a =  6.8453892659396742e-01, /* 0x3fe5e7be, 0x2dd1ebce */
 sin(a) =  6.3231588025173768e-01, /* 0x3fe43bee, 0x834d867a */
ULP: 0.51898405

**Comment by drorspei** [comment]
Ok cool, thanks for the clarifications. 
I wasn't familiar with the term ulp, but I've read up and tested all the numbers that appear in my computations. Indeed everything is correct up to 1ulp. Without knowing enough about computation I was expecting 0.5ulp, but I understand now that that's not reasonable.
Thanks for your library :)
