### ISSUE TITLE
NetBSD support, conflict with built-in definition of __weak_reference

### ISSUE THREAD

**Issue by gufe44** [JuliaMath/openlibm#196]
There is a conflict with the NetBSD built-in macro definition of __weak_reference. Otherwise it compiles fine.

**Comment by ViralBShah** [comment]
Submit a PR?

**Comment by gufe44** [comment]
I was hoping you could point me in a direction before I start touching all those files. Is simply renaming the macro an option?

**Comment by ararslan** [comment]
Oddly enough, it looks to me as though we aren't redefining `__weak_reference` if it already exists: https://github.com/JuliaMath/openlibm/blob/72f33a3bf983dd4ebaf50572b9275ddaec66fae6/src/cdefs-compat.h#L28

Can you post the message(s) you get when compiling on NetBSD?

**Comment by gufe44** [comment]
The NetBSD definition takes only one argument.

**Comment by ViralBShah** [comment]
Fixed in #198
