### ISSUE TITLE
Documentation missing

### ISSUE THREAD

**Issue by allanleal** [JuliaMath/openlibm#202]
Hi, thanks for starting this project. I'm interested to learn more about openlibm, but both website (https://openlibm.org/) and GitHub page does not offer much information on how to use it and what is available to use.

**Comment by ViralBShah** [comment]
It's best to refer to the FreeBSD libm documentation:

https://www.freebsd.org/cgi/man.cgi?query=math&sektion=3&apropos=0&manpath=freebsd
