### ISSUE TITLE
tgammaf(x) should check whether x <= 0x1.18521ep+5

### ISSUE THREAD

**Issue by clairvoyante** [JuliaMath/openlibm#229]
Because :
gamma(0x1.18521ep+5) ~= 3.402 797 ...e38 < FLT_MAX
gamma(nextafterf(0x1.18521ep+5, FLT_MAX)
  = gamma(0x1.185220p+5) ~= 3.402 843 ...e38 > FLT_MAX

So, tgammaf(x) should check whether x <= 0x1.18521ep+5,
then return(tgamma(x))
or raise +INF error.

**Comment by clairvoyante** [comment]
I made a mistake. Sorry.

gamma(nextafterf(0x1.18521ep+5, FLT_MAX)
  = gamma(0x1.185220p+5) ~= 3.402 797 911 565 497 610 ...e38
      < FLT_MAX + 1/2ulp(= 0x1.ffffffp+127) <- not overflow
gamma(nextafterf(0x1.185220p+5, FLT_MAX)
  = gamma(0x1.185222p+5) ~= 3.402 889 871 736 520 656 ...e38
      > FLT_MAX + 1/2ulp <- overflow

So, tgammaf(x) should check whether x <= ~~0x1.18521ep+5~~ 0x1.185220p+5,
then return(tgamma(x))
or ~~raise~~ return +INF ~~error~~.

**Comment by kargl** [comment]
What operating system are you using and what test program?  I get the expected result for both FreeBSD libm and Openlibm on x86_64-*-freebsd.

     ./tlibm_libm -a 0x1.185220p+5 -f tgamma
     x =  3.50401001e+01f, /* 0x420c2910 */
     libm =  inff, /* 0x7f800000 */
     mpfr =  inff, /* 0x7f800000 */
     ULP = inf
     ./tlibm_olibm -a 0x1.185220p+5 -f tgamma
     x =  3.50401001e+01f, /* 0x420c2910 */
     libm =  inff, /* 0x7f800000 */
     mpfr =  inff, /* 0x7f800000 */
     ULP = inf

tlibm_libm is my general libm testing program linked with FreeBSD's libm.  tlibm_olibm is linked against OpenLibm.

**Comment by kargl** [comment]
Note, this simple program

    #include <math.h>
    #include <stdio.h>
    int
    main(void)
    {
       float x, y;
       x = 0x1.185220p+5f;
       y = tgammaf(x);
       printf("tgammaf(%a) = %e\n", x, y);
       return 0;
    }

    % cc -o z -O -pipe -static b.c -lm && ./z
    tgammaf(0x1.18522p+5) = inf
    % cc -o z -O -pipe -static b.c -Lolibm -lopenlibm && ./z
    tgammaf(0x1.18522p+5) = inf

gives the expected result.  How are you doing your testing?

**Comment by clairvoyante** [comment]
I made a mistake(again !). Sorry.

gamma(0x1.185220p+5) ~= ~~3.402 797 911 565 497 610~~ 3.402 843 891 339 645 105 ...e38 > FLT_MAX + 1/2ulp <- overflow
(This check was done in Python and mpmath :

```
from mpmath import mp
mp.dps=34
mp.workprec=256
x=float.fromhex('0x1.185220p+5')
print(mp.gamma(x))
print(float(mp.gamma(x)))
print(float.hex(float(mp.gamma(x))))
```
)
