### ISSUE TITLE
clang i686-w64-windows-gnu weak reference mangling

### ISSUE THREAD

**Issue by jeremyd2019** [JuliaMath/openlibm#237]
Sorry, this is probably pretty esoteric...

I am attempting to build for i686-w64-windows-gnu, and it is failing to link.  After some investigation I found the cause.  Clang is hitting this case:
https://github.com/JuliaMath/openlibm/blob/f052f42bb393918acd6fd51ec1f018c5679dfe30/src/cdefs-compat.h#L61-L66

But, on x86 32-bit Windows, symbols for C functions are prefixed by `_`.  Changing that so that `sym` and `alias` are prefixed by `_` solves the linking there.  That doesn't seems like it would work everywhere though.

In contrast, I think GCC would hit the case:
https://github.com/JuliaMath/openlibm/blob/f052f42bb393918acd6fd51ec1f018c5679dfe30/src/cdefs-compat.h#L73-L75

Which always includes `_` prefixes,,,

See also https://github.com/mingw-w64/mingw-w64/blob/6b62cf66832bd158c67662cd5566413baf35f20e/mingw-w64-headers/crt/_mingw_mac.h#L130 and the lines immediately before that figure out whether the `_` is required or not

**Comment by ViralBShah** [comment]
Could you provide a PR here?
