### ISSUE TITLE
CI architectures

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaMath/openlibm#245]
So, adding the `arch` variable to your build matrix doesn't actually give you a VM with that architecture. The only thing that determines what kind of VM you get is the `runs-on: ${{ matrix.os }}` key.

Details on the available VMs are here: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources

So e.g. `ubuntu-latest` gets you an Ubuntu x86_64 VM. `macos-latest` gets you a macOS x86_64 VM. And `windows-latest` gets you a Windows x86_64 VM.

If you want to e.g. build an x86 build and test it CI, I think you need to install the appropriate 32-bit compiler, and then pass the `ARCH` make variable. 

cc: @ViralBShah @jeremyd2019

**Comment by DilumAluthge** [comment]
For Windows, thanks to @jeremyd2019's work, I think we are doing this correctly, because we are correctly setting up the desired MSYS2 environment. So I think on Windows, we are indeed doing 32-bit building and testing when requested.

But currently, for Linux and macOS, we are always doing x86_64, regardless of the value of the `arch` variable.

**Comment by ViralBShah** [comment]
Thanks. I think I don't want to do any more work on CI - I am satisfied with what we have. If someone wants to enable linux 32-bit CI, that will be nice to have. I feel we have adequate coverage.

How do we get arm/aarch64 support going though? I see https://github.com/marketplace/actions/run-on-archlinuxarm. I used to think that github actions natively supported arm.

**Comment by jeremyd2019** [comment]
Yes, on Windows you are getting proper 32 and 64-bit x86 builds through the `msystem` setting on the setup-msys2 action.  You could theoretically do a cross-compile for Windows aarch64 (or ARM64 as they call it) using llvm-mingw, but you couldn't test it without arm hardware.

**Comment by jeremyd2019** [comment]
> How do we get arm/aarch64 support going though? I see https://github.com/marketplace/actions/run-on-archlinuxarm. I used to think that github actions natively supported arm.

Nope ☹️   All they've got is the ability to run a self-hosted runner on linux aarch64.  No hosted-by-them runners, and no Windows aarch64 (https://github.com/actions/runner/pull/785 has been open quite a while)

**Comment by DilumAluthge** [comment]
I agree that for now, I think we are fine with what we have.

**Comment by jeremyd2019** [comment]
Most people seem to do linux arm as a cross-compile, and test with qemu-user I think.

**Comment by ViralBShah** [comment]
That seems like too much effort. I'm happy with what we have now.
