### ISSUE TITLE
does not build on Windows ARM64

### ISSUE THREAD

**Issue by jeremyd2019** [JuliaMath/openlibm#250]
https://github.com/JuliaMath/openlibm/blob/f88e52a89eb162d2fc0a8abd3ec2c9b6aeea16c3/src/aarch64_fpmath.h#L30-L44

Results in errors because `unsigned long` is 32-bits on Windows.  Could this use `uint64_t`, or does this need some sort of `__LP64__` check like https://github.com/JuliaMath/openlibm/blob/f88e52a89eb162d2fc0a8abd3ec2c9b6aeea16c3/src/fpmath.h#L34-L39 (though I don't see a 32-bit arm equivalent like the x86 case).

After hacking around that I get
```
src/s_cosl.c:44:2: error: "Unsupported long double format"
```

**Comment by jeremyd2019** [comment]
With this compiler, `LDBL_MANT_DIG` is 53.  That doesn't seem right.  Rather like long double is really double.

**Comment by jeremyd2019** [comment]
@mstorsjo is `long double` the same as `double` on `aarch64-w64-windows-gnu`?

**Comment by mstorsjo** [comment]
> @mstorsjo is `long double` the same as `double` on `aarch64-w64-windows-gnu`?

Yes, there’s no 80 bit double on arm, so long double is equal to plain double.

Aarch64 on Linux has a 128 bit long double though, so technically I guess it could be possible to change to that, but it’d be an ABI break, require a bunch of changes throughout mingw-w64-crt, and we’d lose the advantage we have right now, that all the basic types match MSVC.
