### ISSUE TITLE
Questions about openlibm.

### ISSUE THREAD

**Issue by PowerUser1234** [JuliaMath/openlibm#266]
-Does openlibm support these functions: sin, cos, tan, asin, acos, atan, exp, log, log10, cbrt, atan2, pow, sinh, cosh, tanh, hypot, expm1, and log1p?

-Is openlibm different from fdlibm, in regards that it presumes IEEE 754 floating point? Does openlibm in fact NOT allow floating point value errors for return values, the way that fdlibm can?

-Is openlibm multiplatform capable? Could it be compiled and run on Linux/AArch64, Linux/x64, macOS/AArch64, macOS/x64, 
and Windows/x64 with no problems?

**Comment by ararslan** [comment]
> Does openlibm support these functions: [...]

Yes to all you listed. You can find all of these in the `src/` directory.

The answers to your other questions can be found from [openlibm.org](https://openlibm.org), relevant sections reproduced here. Note that the platform support section is also in the repository's README.

> ## History
> The OpenLibm code derives from the [FreeBSD msun](http://svnweb.freebsd.org/base/head/lib/msun/) and [OpenBSD libm](http://cvsweb.openbsd.org/cgi-bin/cvsweb/src/lib/libm/src/) implementations, which in turn derive from [FDLIBM 5.3](http://www.netlib.org/fdlibm/). Over and above that, OpenLibm itself has received a number of patches to make it platform independent and portable.
>
> ## Platform support
> OpenLibm builds on Linux, macOS, Windows, FreeBSD, OpenBSD, NetBSD, and DragonFly BSD. It builds with both GCC and clang. Although largely tested and widely used on the x86 and x86-64 architectures, OpenLibm also supports arm, aarch64, ppc64le, mips, wasm32, and s390(x).
