### ISSUE TITLE
openlibm, fdlibm, Java openjdk?

### ISSUE THREAD

**Issue by PowerUser1234** [JuliaMath/openlibm#272]
-If I want to, can I create a new Java OpenJDK maths class, with a class signature the same as java.lang.StrictMath, 
and build an openjdk language useable calculator class parallel to StrictMath that calls upon openlibm instead of fdlibm, 
resulting in no openjdk floating point errors, by rebuilding the Java OpenJDK, say, version 19, using openlibm instead of
fdlibm?

-Could this be done by dropping in openlibm, and changing the name references to openlibm instead of fdlibm, directly, requiring no other changes, or some changes?

**Comment by ViralBShah** [comment]
In theory, that should work (not knowing much about java myself).
