### ISSUE TITLE
configure: error: libmpfr not found or uses a different ABI (including static vs shared).

### ISSUE THREAD

**Issue by zuoyanzhang** [JuliaMath/openlibm#279]
when I excute $ make, it shows error message "configure: error: libmpfr not found or uses a different ABI (including static vs shared).
make: *** [Makefile:173: deps/mpc-64/herbgrind-install/lib/libmpc.a] Error 1", and the Makefile: 173 is 
![image](https://github.com/JuliaMath/openlibm/assets/93237592/5f783a6a-7b8a-4209-a7b8-7d5bce31e917)
what should I do to solve it? Thanks

**Comment by ViralBShah** [comment]
Doesn't seem related to openlibm.
