### ISSUE TITLE
makefile error

### ISSUE THREAD

**Issue by achan001** [JuliaMath/openlibm#281]
I donwloaded openlibm v0.8.1 and strawberry perl 5.32.1.1
Perl come supplied with gcc 8.3.0 (i686-w64-mingw32)

Using gmake, it did compile to static library, in my old Win7 laptop.
But, it grabbed **i387/s_tan.S** (with inaccurate fptan) rather than **src/s_tan.c**

Test suite was unable to detect this. (all run successfully)

I just manually compile s_tan.c to replace s_tan.S,  Everything work now.
It might be better to fix it in makefile instead.

BTW, very nice math library!

**Comment by ViralBShah** [comment]
If you are able to provide a PR to the build system, it will be helpful, since I do not have access to such a system.
